apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: itta-dev-daemonset
  labels:
    app: itta-dev
spec:
  selector:
    matchLabels:
      app: itta-dev
  template:
    metadata:
      labels:
        app: itta-dev
    spec:
      containers:
        - name: itta-dev
          image: itta/itta.dev:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
