apiVersion: apps/v1
kind: Deployment
metadata:
  name: itta-dev-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itta-dev
  template:
    metadata:
      labels:
        app: itta-dev
    spec:
      containers:
        - name: itta-dev
          env:
            - name: API_ENDPOINT
              value: 'http://stats-manager.default.svc.cluster.local'
          image: itta/itta.dev:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
