apiVersion: v1
kind: Pod
metadata:
  name: stats-manager-pod
  labels:
    app: stats-manager
spec:
  containers:
    - name: stats-manager
      image: itta/stats-manager:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 2784
  nodeSelector:
    node-role.kubernetes.io/master: ''
