apiVersion: v1
kind: Service
metadata:
  name: stats-manager
spec:
  selector:
    app: stats-manager
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 2784
  type: ClusterIP
  dnsPolicy: ClusterFirst
