apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  rules:
    - host: itta.dev
      http:
        paths:
          - pathType: Prefix
            path: '/'
            backend:
              service:
                name: itta-dev
                port:
                  number: 80
    - host: s3.itta.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: external-s3
                port:
                  number: 9000
